Cuda = True
seed = 114514
distributed = False
sync_bn = False
fp16 = False
data_name=''
classes_path = 'model_data/rtts_classes.txt'
anchors_path = 'model_data/yolo_anchors.txt'
anchors_mask = [[3, 4, 5], [1, 2, 3]]
model_path = 'model_data/yolov4_tiny_weights_coco.pth'
input_shape = [416, 416]
phi = 0
pretrained = False
Init_Epoch = 0
Freeze_Epoch = 50
Freeze_batch_size = 8
UnFreeze_Epoch = 300
Unfreeze_batch_size = 16
Freeze_Train = False
Init_lr = 1e-2
Min_lr = Init_lr * 0.01
optimizer_type = "sgd"
momentum = 0.937
weight_decay = 5e-4
lr_decay_type = "cos"
save_period = 10
save_dir = f'logs-{data_name}'
eval_flag = True
eval_period = 10
num_workers = 0
train_annotation_path = f'dataset_split/train_{data_name}.txt'
val_annotation_path = f'dataset_split/test_{data_name}.txt'